/**
 * Logout Controller (Example)
 * @author generated by plugin script
 */
class LogoutController {

  def index = {
    /* ---- save your codes here ----  */
    
    redirect(uri:"/j_acegi_logout")
    render(text:"")
  }
}
